import React, { useState, useEffect } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext'; 
import toast from 'react-hot-toast';
import { FaArrowLeft, FaMagic } from 'react-icons/fa';
import Icon from '../components/Icon';

interface PollResults {
  [key: string]: number;
}

const LLMDashboard = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const meetingId = location.state?.meetingId;
  const { socket } = useAuth(); 

  const [topic, setTopic] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [question, setQuestion] = useState('');
  const [options, setOptions] = useState<string[]>([]);
  const [isPollActive, setIsPollActive] = useState(false);
  const [results, setResults] = useState<PollResults>({});
  const [studentCount, setStudentCount] = useState(0);

  useEffect(() => {
    if (!socket || !meetingId) {
      if (!meetingId) toast.error('No meeting ID found. Redirecting...');
      navigate('/host-dashboard');
      return;
    }

    const handleUpdateResults = (newResults: PollResults) => setResults(newResults);
    const handleUpdateCount = (count: number) => setStudentCount(count);
    const handlePollEnded = () => {
      setIsPollActive(false);
      setTopic('');
      setQuestion('');
      setOptions([]);
      toast("Poll has ended.");
    };

    socket.on('update-results', handleUpdateResults);
    socket.on('update-student-count', handleUpdateCount);
    socket.on('poll-ended', handlePollEnded);

    return () => {
      socket.off('update-results', handleUpdateResults);
      socket.off('update-student-count', handleUpdateCount);
      socket.off('poll-ended', handlePollEnded);
    };
  }, [socket, meetingId, navigate]);

  const generatePollWithAI = () => {
    if (!topic.trim()) {
      return toast.error("Please enter a topic.");
    }
    setIsGenerating(true);

    setTimeout(() => {
      setQuestion(`What is the main advantage of ${topic}?`);
      setOptions([
        "Performance",
        "Readability",
        "Scalability",
        "Community Support"
      ]);
      setIsGenerating(false);
      toast.success("Poll generated by AI!");
    }, 1500);
  };

  const startPoll = () => {
    if (!question || options.length < 2) {
      toast.error("Poll must have a question and at least two options.");
      return;
    }
    if (socket) {
      const poll = { question, options };
      socket.emit('host-start-poll', { meetingId, poll });
      setIsPollActive(true);
      toast.success('Poll started!');
    }
  };

  const endPoll = () => {
    if (socket) {
      socket.emit('host-end-poll', { meetingId });
    }
  };

  const totalVotes = Object.values(results).reduce((sum, count) => sum + count, 0);

  return (
    <div className="p-8 bg-gray-100 min-h-[calc(100vh-64px)]">
      <div className="max-w-4xl mx-auto">
        <button
          onClick={() => navigate('/host-dashboard')}
          className="flex items-center gap-2 text-sm text-gray-600 hover:text-gray-900 mb-4"
        >
          <Icon as={FaArrowLeft} /> Back to Dashboard
        </button>
        <div className="bg-white p-6 rounded-lg shadow-md">
          <div className="flex justify-between items-center mb-4">
            <h1 className="text-3xl font-bold text-gray-800">LLM Polling Session</h1>
            <span className="text-lg font-medium text-gray-600">
              Connected Students: {studentCount}
            </span>
          </div>

          {!isPollActive ? (
            <div className="space-y-4">
              {/* Step 1: Topic Input */}
              {!question && (
                <div className="p-4 border-2 border-dashed rounded-lg space-y-3">
                  <label htmlFor="topic" className="block text-lg font-medium text-purple-700">
                    1. Enter a Topic for the AI
                  </label>
                  <input
                    id="topic"
                    value={topic}
                    onChange={(e) => setTopic(e.target.value)}
                    placeholder="e.g., React Hooks"
                    className="mt-1 block w-full text-lg p-2 border border-gray-300 rounded-md shadow-sm"
                  />
                  <button
                    onClick={generatePollWithAI}
                    disabled={isGenerating}
                    className="w-full flex justify-center items-center gap-2 py-3 px-4 text-lg font-semibold text-white bg-purple-600 hover:bg-purple-700 rounded-md shadow-sm disabled:bg-purple-300"
                  >
                    {isGenerating ? 'Generating...' : 'Generate Poll with AI'} <Icon as={FaMagic} />
                  </button>
                </div>
              )}

              {/* Step 2: Review and Start */}
              {question && (
                <div className="p-4 border-2 border-dashed rounded-lg space-y-3">
                  <h3 className="text-lg font-medium text-purple-700">
                    2. Review and Start the Generated Poll
                  </h3>
                  <p className="text-xl font-semibold">{question}</p>
                  <ul className="list-disc list-inside ml-5">
                    {options.map((opt) => (
                      <li key={opt}>{opt}</li>
                    ))}
                  </ul>
                  <button
                    onClick={startPoll}
                    className="w-full py-3 px-4 text-lg font-semibold text-white bg-blue-600 hover:bg-blue-700 rounded-md shadow-sm"
                  >
                    Start This Poll
                  </button>
                </div>
              )}
            </div>
          ) : (
            <div className="space-y-4">
              <h2 className="text-2xl font-semibold text-gray-800">{question}</h2>
              <p className="text-gray-600">Live results... Total Votes: {totalVotes}</p>
              <div className="space-y-3">
                {Object.entries(results).map(([option, votes]) => {
                  const percentage = totalVotes > 0 ? (votes / totalVotes) * 100 : 0;
                  return (
                    <div key={option}>
                      <div className="flex justify-between items-center mb-1">
                        <span className="font-medium text-gray-700">{option}</span>
                        <span className="text-sm font-bold text-gray-600">{votes} vote(s)</span>
                      </div>
                      <div className="w-full bg-gray-200 rounded-full h-6">
                        <div
                          className="bg-purple-500 h-6 rounded-full text-center text-white font-bold transition-all duration-500"
                          style={{ width: `${percentage}%` }}
                        >
                          {percentage > 10 && `${percentage.toFixed(0)}%`}
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
              <button
                onClick={endPoll}
                className="w-full mt-4 py-3 px-4 text-lg font-semibold text-white bg-red-600 hover:bg-red-700 rounded-md shadow-sm"
              >
                End Poll
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default LLMDashboard;
